# Generated by Django 6.0.3 on 2026-04-02 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominales', models.IntegerField()),
                ('precio_total_pesos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('precio_usd_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activo')),
            ],
        ),
    ]
