# Generated by Django 6.0.3 on 2026-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_operacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='precio_usd_momento',
            new_name='dolar_ccl',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='precio_total_pesos',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='es_cedear',
        ),
        migrations.AddField(
            model_name='activo',
            name='ratio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operacion',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares')], default='ARS', max_length=3),
        ),
    ]
