# Generated by Django 6.0.3 on 2026-04-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_precio_usd_momento_operacion_dolar_ccl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='precio_total',
            new_name='precio_unitario',
        ),
    ]
