# Generated by Django 6.0.3 on 2026-04-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_precio_total_operacion_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_invertido_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_actual_usd', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominales', models.IntegerField()),
                ('precio_usd_diario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activo')),
                ('snapshot_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.historicoportfolio')),
            ],
        ),
    ]
