# Generated by Django 6.0.3 on 2026-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historicoportfolio_historicoactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoactivo',
            name='cantidad_invertida_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
