# Generated by Django 6.0.3 on 2026-04-05 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_historicoactivo_cantidad_invertida_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_ars', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_nominales', models.IntegerField(default=0)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'activo')},
            },
        ),
    ]
