# Generated by Django 6.0.3 on 2026-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_operacion_usuario_cuenta_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], default='COMPRA', max_length=10),
        ),
    ]
