# Generated by Django 6.0.3 on 2026-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_operacion_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='precio_actual_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
