# Generated by Django 6.0.3 on 2026-04-05 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activo_precio_actual_usd_activo_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoportfolio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
