# Generated by Django 6.0.3 on 2026-04-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_historicoportfolio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='ganancia_realizada_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
