# Generated by Django 6.0.3 on 2026-04-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_operacion_ganancia_realizada_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='ganancia_realizada_historica_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
