# Generated by Django 6.0.3 on 2026-04-07 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cuenta_ganancia_realizada_historica_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoportfolio',
            name='precio_spy_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicoportfolio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='historicoportfolio',
            unique_together={('usuario', 'fecha')},
        ),
    ]
