# Generated by Django 6.0.3 on 2026-04-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_historicoportfolio_precio_spy_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoportfolio',
            name='costo_base_sombra_usd',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicoportfolio',
            name='valor_sombra_spy_usd',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
