# Generated by Django 6.0.3 on 2026-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_historicoportfolio_costo_base_sombra_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='precio_promedio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
